### ISSUE TITLE
Woot Factory Exotics not appearing

### ISSUE THREAD

**Issue by ResonantFlux1** [SmashingModsTogether/SMT-Issues#12]
The exotic blocks from the Woot mod are supposed to have a chance of spawning in end cities, but after searching upwards of 10-15 end cities I have not encountered a single one. So either they are way rarer than they should be, or they aren't spawning at all.

**Comment by Dark-Arcana** [comment]
Can you give me a list of all woot blocks and items that should be spawning in loot tables and which loot tables they should be in? I can use that to add them back manually in the event that they don't spawn naturally. Thanks.

**Comment by ResonantFlux1** [comment]
they should appear in the End City Treasure loot table. The block names are listed as woot:exotic_a, woot:exotic_b, woot:exotic_c, woot:exotic_d, woot:exotic_e.

**Comment by Dark-Arcana** [comment]
I discussed this issue on the Discord:

> As for woot exotics in end cities, I think Better End Forge actually nukes the end cities, as in they don't spawn correctly.
> So what you are finding are end towers and catacombs from the outer end.
> https://www.planetminecraft.com/data-pack/end-city-for-better-end-forge-port/
> I'm going to add this datapack.
> And I'm also going to add new loot modifier tables to add the exotics to end structures.

**Comment by Dark-Arcana** [comment]
I'm going to leave the datapack in because it's awesome, but it didn't fix anything.

Woot specifically tries to spawn loot as a loot modifier into "minecraft:chest". Since we are using lootr chests, it doesn't work. So I added a new loot table that has nearly the same conditions as the mod (without the random chance of 15%) and added it to the custom end city loot table we're using. This fixes the issue.
