### ISSUE TITLE
Crafting output not visible in crafting table

### ISSUE THREAD

**Issue by TheDarkPreacher** [SmashingModsTogether/SMT-Issues#24]
**Describe the issue**
In version 1.1.2-hotfix-lite, when using a crafting table, when making any crafting recipe, like two planks into sticks, the output is not visible in the crafting table GUI.

**To Reproduce**
1. Start new world
2. punch wood, make crafting table
3. craft anything in crafting table, and look at output.

**Expected behavior**
I expected normal crafting behavior.

**Screenshots**

**Game Environment(please complete the following information):**
- Operating System: Windows 11
- Java Version: jre-1.8.0_311
- Modpack Version: 1.1.2-hotfix-lite
- Mod causing issue if applicable: Unsure

**Additional context**
Add any other context about the problem here. Do you have a crash report / latest.log / debug.log file? Please upload the file and provide a download link or use gist / pastebin. **Do not copy and paste log files into your issue!**.

**Comment by Dark-Arcana** [comment]
I have tested and confirmed that this issue is present with Visual Workbench version 1.0.5-1.16.5 and newer. Downgrading to 1.0.3-1.16.5, the issue is no longer present.

I'm not entirely sure if this is the fault of Visual Workbench or some interaction between this mod and some other. This issue should be cross posted to their Issue page to report it.

**Comment by Fuzss** [comment]
From what I've heard that's an issue with FastWorkbench Minus Replacement. I'll look into it.

**Comment by Dark-Arcana** [comment]
Ahh yes, we are indeed using that mod for performance reasons. I would appreciate you looking into it, thanks!

**Comment by TheDarkPreacher** [comment]
Closing #24, fixed after an update.
