### ISSUE TITLE
Please add essential mods

### ISSUE THREAD

**Issue by LuciusV** [SmashingModsTogether/SMT-Issues#32]
Hi! Nice job on modpack!
I suggest adding Mekanism and Industrial Foregoing, every tech modpack had them...
Also please consider Mystical Agriculture and Botany pots

**Comment by Dark-Arcana** [comment]
Hello and thanks for liking the modpack!

Mekanism, Industrial Foregoing, Mystical Agriculture; these mods are all very popular and as such are in every single modpack. I've shied away from adding a lot of really popular content based mods like these *because* they are ubiquitous. If every pack shares these content mods, then every pack is nearly the same. So to make something different and unique, I didn't include them.

I've included mods that fulfil every niche however, and I will not be adding these specifically. Can you give me a good reason why I should? I'm willing to hear you out!

**Comment by LuciusV** [comment]
My reason is I automate everything I can and automation relies heavily on these mods
Also I do ore X5 and reactors every time

**Comment by Dark-Arcana** [comment]
I understand that. For yourself, you can easily add those mods, drag and drop. But what I meant was, what good reason is there to add the mod that it would enhance the modpack for everyone? I'm honestly not going to add any of these mods. But you can try to change my mind.

**Comment by Dark-Arcana** [comment]
I've created two new issues for the mods that we might be willing to add. See them here:

https://github.com/SmashingModsTogether/SMT-Issues/issues/51
https://github.com/SmashingModsTogether/SMT-Issues/issues/52

And if you have more suggestions, please let us know. We're working on this now before we move on to make our next pack.
