### ISSUE TITLE
Remove Genetic Animals

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#35]
**Remove the Genetic Animals mod**
People tend to not like the mechanics of the mod which can get in the way of having fun playing. Discuss below why you would or would not like to remove this mod.

**Comment by JartanFTW** [comment]
I think we should remove it.

There is no point to it. It feels like a roleplay mod. You can selectively breed chickens to make a ton of feathers but why would you really need a ton of feathers, and why not just use a spawner or woot instead?
You can selectively breed cows to make a ton of beed/leather, but the same question applies.

I was far more interested in the mod at first because I thought you could create things like diamond cows and such, but from what I understand you can't- which means that there are better options for basically every resource that Genetic Animals helps you get.

**Comment by Dark-Arcana** [comment]
Yeah I definitely agree with everything you said. Basically everyone I talk to seems to dislike this mod. That makes it a prime candidate for removal!

**Comment by Dark-Arcana** [comment]
Removed.
