### ISSUE TITLE
Add Industrial Foregoing

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#52]
Describe your feature request
Let's investigate adding [this mod](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing) to see if it fits.

What problem does your feature solve?

This mod was requested by a user in a separate issue. But this adds even more ways to farm specific items. Keep in mind that if we add Industrial Foregoing, we would also need to look into adding the [Integration Foregoing](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing) mod as well.

**Comment by iarspider** [comment]
Here is my opinion on this mod:
* Plant farming (Hydroponic bed, Plant gatherer/sower/harverster, fertilizer): can be done via Create. Mass fertilizing can be done via Blood Magic
* Animal farming (Animal feeder, Animal Rancher, Animal baby separator, technically Sewer and Sewage composter): useful if you want to get a lot of meat for your burgers. Sewer is a renewable source of fertilizer (not exactly a problem in this modpack)
* Mob farming (Mob duplicator, Mob Crusher): again, Create. Not sure though that Create drills give player-only drops though. And Apotheosis for spawning mobs that you want.
* While still in Mob farming category, Mob slaughter Factory can be used to double (?) ores. Tinker's, Thermal and Create can handle that (although Create's method is not exactly doubling).
* Wither builder: ok, that one is useful and kind of hard to replace (does BM have teleposers is this version? Haven't played with BM since 1.7.10, I think)
* Different weird generators: most produce 40 RF/t, same as . Do we need more ways to produce power in this modpack? 
* Infinity backpack: Sophisticated backpacks with upkeep. 
* Other infinity tools: yes, please!
* Marine fisher: again, yes please! Especially if it will produce Aquaculture fishes.
* Enchantment machines (E. Applicator, E. Extractor, E. Sorter, E. Factory): if it supports insane enchantments from Apotheosis - very much YES
* Stonework factory: good for servers, but not as fun as making a maze of pipes/conveyors to do the same thing
* Black hole unit/tank: Yet another drawer alternative
* Lasers: we have them already
* Other stuff (block/fluid placer, resourceful furnace, ...): I think this is achievable with other mods already in the pack.

So, overall: would enjoy having it in the pack, but a lot of things is already doable with existing mods (or even vanilla).

**Comment by Dark-Arcana** [comment]
I prefer not to add things that have too much overlap. So if this mod does a bunch of stuff that other mods are already doing, it might not be  a good fit. The exception to the rule is if it is a more focused attempt at that niche while other mods are doing a lot of different things (like how create can do basically anything). What I see based on your feedback is that there are some unique things that this does that you'd like to see in the pack, but the issue comes down to the mod doing so much stuff that is already being done well by other mods. So I don't know if this is a good fit.

What do you think?

**Comment by Timbroglio** [comment]
The biggest things I'm seeing that IF would add that we don't currently have are automated fishing and automated enchantment. Maybe we can find alternatives for those that work within the pack, without adding a lot of extras?

**Comment by Dark-Arcana** [comment]
That's a good possibility. I'm open to suggestions.

**Comment by iarspider** [comment]
> automated enchantment

Also full (lossless) disenchantment and enchantment sorting/storage

**Comment by Timbroglio** [comment]
Evilcraft has lossless disenchantment, Apotheosis has the library for sorting & storage.

**Comment by castillao** [comment]
i love the infinity drill from industrial foregoin, so i would like this

**Comment by JartanFTW** [comment]
> Here is my opinion on this mod:
> 
> * Plant farming (Hydroponic bed, Plant gatherer/sower/harverster, fertilizer): can be done via Create. Mass fertilizing can be done via Blood Magic
> * Animal farming (Animal feeder, Animal Rancher, Animal baby separator, technically Sewer and Sewage composter): useful if you want to get a lot of meat for your burgers. Sewer is a renewable source of fertilizer (not exactly a problem in this modpack)
> * Mob farming (Mob duplicator, Mob Crusher): again, Create. Not sure though that Create drills give player-only drops though. And Apotheosis for spawning mobs that you want.
> * While still in Mob farming category, Mob slaughter Factory can be used to double (?) ores. Tinker's, Thermal and Create can handle that (although Create's method is not exactly doubling).
> * Wither builder: ok, that one is useful and kind of hard to replace (does BM have teleposers is this version? Haven't played with BM since 1.7.10, I think)
> * Different weird generators: most produce 40 RF/t, same as . Do we need more ways to produce power in this modpack?
> * Infinity backpack: Sophisticated backpacks with upkeep.
> * Other infinity tools: yes, please!
> * Marine fisher: again, yes please! Especially if it will produce Aquaculture fishes.
> * Enchantment machines (E. Applicator, E. Extractor, E. Sorter, E. Factory): if it supports insane enchantments from Apotheosis - very much YES
> * Stonework factory: good for servers, but not as fun as making a maze of pipes/conveyors to do the same thing
> * Black hole unit/tank: Yet another drawer alternative
> * Lasers: we have them already
> * Other stuff (block/fluid placer, resourceful furnace, ...): I think this is achievable with other mods already in the pack.
> 
> So, overall: would enjoy having it in the pack, but a lot of things is already doable with existing mods (or even vanilla).

Based on @iarspider's phenomenal summary, I am in support of adding this mod.

Although there is some overlap, I think that these can just be disabled- leaving the other additions. 
I think that the usefulness of the additions far outweighs the cost of having to disable the overlap.
I also think that it isn't necessarily a good idea to disable ALL the overlap, just the ones that feel unbalanced as an alternative where one is clearly superior. Just because I can use blood magic to mass-fertilize doesn't mean I actually want to progress blood magic, right? Edit: For example, the new generators are obviously worse than out Powah ones and add nothing to the table; These would be disabled. Infinity Backpacks though, are a valid and useful ALTERNATIVE to the backpacks we have currently.

**Comment by iarspider** [comment]
Just wanted to do a small update: I totally forgot that one can strip enchantments using Pneumaticraft! Doing it the Evilcraft way requires a lot of blood (in my current LP I have two diamond chests full of stuff that I need to disenchant - most with 2+ enchantments, which means Apotheosis' Tome is not an option - it will gladly strip that stupid Tinted enchantment instead of Efficiency/Fortune)

But still blackhole stuff is nice, infinity drill will help with finding all that Dark Ore, etc, etc

**Comment by Timbroglio** [comment]
After a bit of testing, this mod seems to add far too much overlap to be worth including. It's got a few additional features but is largely redundant.
